server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customer
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/fraud
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true